[package]
name = "casino-rs"
version = "0.1.0"
edition = "2024"
authors = ["Bart Carroll <bart.a.carroll@gmail.com>"]

[features]
default = ["python"]
python = ["pyo3/extension-module"]

[dependencies]
rand = "0.9.2"

pyo3 = { version = "0.26.0", features = ["extension-module"] }